# Generated by Django 6.0.1 on 2026-01-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='제품명')),
                ('ingredient_name', models.CharField(max_length=200, verbose_name='성분명')),
                ('efficacy', models.CharField(choices=[('antipyretic', '해열진통제'), ('digestive', '소화제'), ('cold', '감기약'), ('antibiotic', '항생제'), ('vitamin', '비타민'), ('dermatologic', '피부약'), ('other', '기타')], max_length=50, verbose_name='효능/효과')),
                ('dosage', models.TextField(verbose_name='용법/용량')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='제조사')),
                ('precautions', models.TextField(verbose_name='주의사항')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '의약품',
                'verbose_name_plural': '의약품',
                'ordering': ['-created_at'],
            },
        ),
    ]
